server:
  port: 4060

spring:
  application:
    name: admin-service
  
  profiles:
    active: docker
  
  datasource:
    url: jdbc:postgresql://${DROPLET1_IP}:${POSTGRES_PORT:5432}/admin_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  
  security:
    oauth2:
      resourceserver:
        jwt:
          #   THIS NEEDS TO BE keycloak URL
          issuer-uri: ${KEYCLOAK_ISSUER:https://134.122.73.157.nip.io/realms/stockfellow}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:https://134.122.73.157.nip.io/realms/stockfellow/protocol/openid-connect/certs}

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Africa/Johannesburg

logging:
  level:
    com.stockfellow.adminservice: DEBUG
    com.stockfellow.adminservice.config: TRACE
    # org.springframework.security: TRACE
    # org.springframework.security.oauth2: TRACE
    org.springframework.web: DEBUG
    # org.springframework.web.filter: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

keycloak:
  auth-server-url: ${KEYCLOAK_URL}
  realm: stockfellow
  resource: admin-service-client
  credentials:
    secret: "q03cb0bMVy672D6UWU485vWLe55ndX75"

# Service URLs for inter-service communication
services:
  user-service:
    url: ${USER_SERVICE_URL:http://user-service:4020}
  group-service:
    url: ${GROUP_SERVICE_URL:http://group-service:4040}
  transaction-service:
    url: ${TRANSACTION_SERVICE_URL:http://transaction-service:4080}