# User Service Configuration - Simple University Project
spring:
  application:
    name: user-service
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${DROPLET1_IP:-postgres}:5432/userservice_db
    username: ${POSTGRES_USER:-postgres}
    password: ${POSTGRES_PASSWORD:-postgres}
    
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${JPA_SHOW_SQL:false}
    
  # File Upload
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Server Configuration
server:
  port: ${USER_SERVICE_PORT:4020}

# Security
# spring:
#   security:
#     oauth2:
#       resourceserver:
#         jwt:
#           issuer-uri: ${KEYCLOAK_ISSUER:http://keycloak:8080/realms/stockfellow}
#           jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://keycloak:8080/realms/stockfellow/protocol/openid-connect/certs}

# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info

# Logging 
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.stockfellow: ${LOGGING_LEVEL_APP:DEBUG}