# droplet3-services.yml
# Business services: User, Group, Transaction, Notification services
services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    ports:
      - "${USER_SERVICE_PORT:-4020}:4020"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DROPLET1_IP}:5432/userservice_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - KEYCLOAK_JWKS_URI=http://${DROPLET2_IP}:8080/realms/stockfellow/protocol/openid_connect/certs
      - KEYCLOAK_ISSUER=http://${DROPLET2_IP}:8080/realms/stockfellow
      - LOGGING_LEVEL_ROOT=WARN
      - LOGGING_LEVEL_COM_STOCKFELLOW=INFO
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=userservice_db 
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4020/actuator/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 90s
    restart: unless-stopped

  group-service:
    build:
      context: ./group-service
      dockerfile: Dockerfile
    container_name: group-service
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.125'
          memory: 256M
    depends_on:
      - user-service
    ports:
      - "${GROUP_SERVICE_PORT:-4040}:4040"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGODB_URI=${GROUP_SERVICE_MONGODB_URI}
      - KEYCLOAK_ISSUER=http://${DROPLET2_IP}:8080/realms/stockfellow
      - KEYCLOAK_JWKS_URI=http://${DROPLET2_IP}:8080/realms/stockfellow/protocol/openid_connect/certs
      - USER_SERVICE_URL=http://localhost:4020
      - LOGGING_LEVEL_ROOT=WARN
      - LOGGING_LEVEL_COM_STOCKFELLOW=INFO
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4040/actuator/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 90s
    restart: unless-stopped

  transaction-service:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    container_name: transaction-service
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    depends_on:
      - group-service
      - user-service
    ports:
      - "${TRANSACTION_SERVICE_PORT:-4080}:4080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TRANSACTIONDB_URI=${TRANSACTIONDB_URI}
      - TRANSACTIONDB_USER=${TRANSACTIONDB_USER}
      - TRANSACTIONDB_PASS=${TRANSACTIONDB_PASS}
      - PAYSTACK_TEST_API_KEY=${PAYSTACK_TEST_API_KEY}
      - CALLBACK_BASE_URL=${PAYSTACK_CALLBACK_URL}
      - KEYCLOAK_ISSUER=http://${DROPLET2_IP}:8080/realms/stockfellow
      - KEYCLOAK_JWKS_URI=http://${DROPLET2_IP}:8080/realms/stockfellow/protocol/openid_connect/certs
      - USER_SERVICE_URL=http://localhost:4020
      - GROUP_SERVICE_URL=http://localhost:4040
      - LOGGING_LEVEL_ROOT=WARN
      - LOGGING_LEVEL_COM_STOCKFELLOW=INFO
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4080/actuator/health || exit 1"]
      interval: 45s
      timeout: 10s
      retries: 3
      start_period: 90s
    restart: unless-stopped

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    depends_on:
      - group-service
    ports:
      - "${NOTIFICATION_SERVICE_PORT:-4050}:4050"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DROPLET1_IP}:5432/notification_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - ACTIVEMQ_BROKER_URL=tcp://${DROPLET1_IP}:61616
      - ACTIVEMQ_USER=admin
      - ACTIVEMQ_PASSWORD=admin
      - SERVICES_GROUP_SERVICE_URL=http://localhost:4040
      - SERVICES_USER_SERVICE_URL=http://localhost:4020
      - LOGGING_LEVEL_ROOT=WARN
      - LOGGING_LEVEL_COM_STOCKFELLOW=INFO
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=notification_db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4050/actuator/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
    restart: unless-stopped