# droplet3-services.yml
# Business services: User, Group, Transaction, Notification services
services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    ports:
      - "${USER_SERVICE_PORT:-4020}:4020"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DROPLET1_IP}:5432/userservice_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - KEYCLOAK_JWKS_URI=${KEYCLOAK_JWKS_URI}
      - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}
      - LOGGING_LEVEL_ROOT=WARN
      - LOGGING_LEVEL_COM_STOCKFELLOW=INFO
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=userservice_db 
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4020/actuator/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 90s
    restart: unless-stopped

  group-service:
    build:
      context: ./group-service
      dockerfile: Dockerfile
    container_name: group-service
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.125'
          memory: 256M
    depends_on:
      - user-service
    ports:
      - "${GROUP_SERVICE_PORT:-4040}:4040"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGODB_URI=${GROUP_SERVICE_MONGODB_URI}
      - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}
      - KEYCLOAK_JWKS_URI=${KEYCLOAK_JWKS_URI}
      - USER_SERVICE_URL=http://localhost:4020
      - LOGGING_LEVEL_ROOT=WARN
      - LOGGING_LEVEL_COM_STOCKFELLOW=INFO
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4040/actuator/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 90s
    restart: unless-stopped

  transaction-service:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    container_name: transaction-service
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    depends_on:
      - group-service
      - user-service
    ports:
      - "${TRANSACTION_SERVICE_PORT:-4080}:4080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TRANSACTIONDB_URI=${TRANSACTIONDB_URI}
      - TRANSACTIONDB_USER=${TRANSACTIONDB_USER}
      - TRANSACTIONDB_PASS=${TRANSACTIONDB_PASS}
      - PAYSTACK_TEST_API_KEY=${PAYSTACK_TEST_API_KEY}
      - CALLBACK_BASE_URL=${PAYSTACK_CALLBACK_URL}
      - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}
      - KEYCLOAK_JWKS_URI=${KEYCLOAK_JWKS_URI}
      - USER_SERVICE_URL=http://localhost:4020
      - GROUP_SERVICE_URL=http://localhost:4040
      - LOGGING_LEVEL_ROOT=WARN
      - LOGGING_LEVEL_COM_STOCKFELLOW=INFO
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4080/actuator/health || exit 1"]
      interval: 45s
      timeout: 10s
      retries: 3
      start_period: 90s
    restart: unless-stopped

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    depends_on:
      - group-service
    ports:
      - "${NOTIFICATION_SERVICE_PORT:-4050}:4050"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DROPLET1_IP}:5432/notification_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - ACTIVEMQ_BROKER_URL=tcp://${DROPLET1_IP}:61616
      - ACTIVEMQ_USER=admin
      - ACTIVEMQ_PASSWORD=admin
      - SERVICES_GROUP_SERVICE_URL=http://localhost:4040
      - SERVICES_USER_SERVICE_URL=http://localhost:4020
      - LOGGING_LEVEL_ROOT=WARN
      - LOGGING_LEVEL_COM_STOCKFELLOW=INFO
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=notification_db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4050/actuator/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
    restart: unless-stopped
  
  admin-service:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    container_name: admin-service
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.125'
          memory: 256M
    depends_on:
      - user-service
      - group-service
      - transaction-service
    ports:
      - "${ADMIN_SERVICE_PORT:-4060}:4060"
    environment:
      - SERVER_PORT=4060
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DROPLET1_IP}:${POSTGRES_PORT:5432}/admin_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-password}
      - KEYCLOAK_ISSUER=https://134.122.73.157.nip.io/realms/stockfellow
      - KEYCLOAK_JWKS_URI=https://134.122.73.157.nip.io/realms/stockfellow/protocol/openid-connect/certs
      - KEYCLOAK_URL=https://134.122.73.157.nip.io
      - USER_SERVICE_URL=http://user-service:4020
      - GROUP_SERVICE_URL=http://group-service:4040
      - TRANSACTION_SERVICE_URL=http://transaction-service:4080
      - JVM_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5010
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4060/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Admin Front end
  admin-frontend:
    build:
      context: ./apps/web-app
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
        - VITE_KEYCLOAK_URL=${KEYCLOAK_AUTH_SERVER_URL}
        - VITE_KEYCLOAK_REALM=${KEYCLOAK_REALM:-stockfellow}
        - VITE_KEYCLOAK_CLIENT_ID=${KEYCLOAK_FRONTEND_CLIENT_ID}
    container_name: admin-frontend
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.125'
          memory: 256M
    depends_on:
      - admin-service
    ports:
      - "${ADMIN_FRONTEND_PORT:-3001}:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped