version: '3.8'

# Minimal services needed for ID verification testing
services:
  # PostgreSQL Database for Keycloak
  postgres:
    image: postgres:15
    container_name: keycloak-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-keycloak}
      POSTGRES_USER: ${POSTGRES_USER:-keycloak}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-keycloak}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - stockfellow-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-keycloak}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # PostgreSQL Database for Alfresco (needed for document storage)
  alfresco-postgres:
    image: postgres:15
    container_name: alfresco-postgres
    volumes:
      - alfresco_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco123
    ports:
      - "5435:5432"
    networks:
      - stockfellow-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "alfresco"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching (used by API Gateway)
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - stockfellow-net
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    command: redis-server ${REDIS_PASSWORD:+--requirepass $REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Alfresco Search Services (required for Alfresco)
  alfresco-search:
    image: alfresco/alfresco-search-services:2.0.8.1
    container_name: alfresco-search
    environment:
      SOLR_ALFRESCO_HOST: alfresco-content-repository
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: alfresco-search
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: secret
      JAVA_TOOL_OPTIONS: "-Dalfresco.secureComms.secret=secret"
    ports:
      - "8983:8983"
    networks:
      - stockfellow-net
    volumes:
      - alfresco_search_data:/opt/alfresco-search-services/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/admin/cores"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Alfresco Content Repository (for document storage)
  alfresco-content-repository:
    image: alfresco/alfresco-content-repository-community:23.2.1
    container_name: alfresco-content-repository
    depends_on:
      - alfresco-postgres
      - alfresco-search
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=mp6yc0UD9e
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=oKIWzVdEdA
        -Dmetadata-keystore.metadata.algorithm=DESede
      JAVA_OPTS: >-
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
        -Ddb.password=alfresco123
        -Ddb.url=jdbc:postgresql://alfresco-postgres:5432/alfresco
        -Dsolr.host=alfresco-search
        -Dsolr.port=8983
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=secret
        -Dcsrf.filter.enabled=false
        -Dalfresco.restApi.basicAuthScheme=true
        -Dauthentication.protection.enabled=false
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
    ports:
      - "8080:8080"
    networks:
      - stockfellow-net
    volumes:
      - alfresco_acs_data:/usr/local/tomcat/alf_data
      - ./alfresco/keystore:/usr/local/tomcat/shared/classes/alfresco/extension/keystore
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/alfresco/api/-default-/public/alfresco/versions/1/probes/-ready-"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  # Keycloak for authentication
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-keycloak}
      KC_DB_USERNAME: ${POSTGRES_USER:-keycloak}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-keycloak}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_LOG_LEVEL: INFO
    ports:
      - "${KEYCLOAK_PORT:-8180}:8080"
    networks:
      - stockfellow-net
    volumes:
      - ./services/api-gateway/realm-exports:/opt/keycloak/data/import
    command: start-dev --import-realm

  # User Service (the main service we're testing)
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile.dev
    container_name: user-service
    depends_on:
      - keycloak
      - alfresco-content-repository
    ports:
      - "${USER_SERVICE_PORT:-4000}:4000"
      - "${USER_SERVICE_DEBUG_PORT:-5005}:5005"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_DATA_MONGODB_URI=${USER_SERVICE_MONGODB_URI:-mongodb://localhost:27017/userservice_test}
      - KEYCLOAK_JWKS_URI=http://keycloak:8080/realms/stockfellow/protocol/openid-connect/certs
      - KEYCLOAK_ISSUER=http://keycloak:8080/realms/stockfellow
      - ALFRESCO_BASE_URL=http://alfresco-content-repository:8080/alfresco
      - ALFRESCO_USERNAME=admin
      - ALFRESCO_PASSWORD=admin
      - ALFRESCO_SITE_NAME=stockfellow
      - JVM_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM_STOCKFELLOW=DEBUG
    networks:
      - stockfellow-net
    volumes:
      - ./services/user-service/src:/app/src
      - ./services/user-service/pom.xml:/app/pom.xml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  stockfellow-net:
    driver: bridge

volumes:
  postgres_data:
  alfresco_postgres_data:
  redis_data:
  alfresco_acs_data:
  alfresco_search_data:
