version: '3.8'

services:
  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - stockfellow-net
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server ${REDIS_PASSWORD:+--requirepass $REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # PostgreSQL Database for Keycloak
  postgres:
    image: postgres:15
    container_name: keycloak-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - stockfellow-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # PostgreSQL Database for Notification Service
  notification-postgres:
    image: postgres:15
    container_name: notification-postgres
    volumes:
      - notification_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    networks:
      - stockfellow-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ActiveMQ
  activemq:
    image: apache/activemq-artemis:latest-alpine
    container_name: activemq
    ports:
      - "61616:61616"  # OpenWire protocol
      - "8161:8161"    # Web console
      - "5672:5672"    # AMQP
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
    networks:
      - stockfellow-net
    volumes:
      - activemq_data:/var/lib/artemis-instance
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8161/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Keycloak 
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_SPI_EVENTS_LISTENER_USER_SYNC_EVENT_LISTENER_USER_SERVICE_URL: ${USER_SERVICE_URL}
      KC_LOG_LEVEL: ${KEYCLOAK_LOG_LEVEL:-INFO}
    ports:
      - "${KEYCLOAK_PORT}:8080"
    networks:
      - stockfellow-net
    volumes:
      - ./services/api-gateway/realm-exports:/opt/keycloak/data/import
      - ./keycloak-extensions/:/opt/keycloak/providers/
    command: start-dev --import-realm

  # API Gateway (Java Spring Boot)
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    depends_on:
      - keycloak
      - redis
    ports:
      - "${API_GATEWAY_PORT}:3000"
      - "${API_GATEWAY_DEBUG_PORT}:5007"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - KEYCLOAK_AUTH_SERVER_URL=${KEYCLOAK_AUTH_SERVER_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_GATEWAY_CLIENT_ID=${KEYCLOAK_GATEWAY_CLIENT_ID}
      - KEYCLOAK_GATEWAY_CLIENT_SECRET=${KEYCLOAK_GATEWAY_CLIENT_SECRET}
      - KEYCLOAK_FRONTEND_CLIENT_ID=${KEYCLOAK_FRONTEND_CLIENT_ID}
      - KEYCLOAK_FRONTEND_REDIRECT_URI=${KEYCLOAK_FRONTEND_REDIRECT_URI}
      - KEYCLOAK_ADMIN_USERNAME=${KEYCLOAK_ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_ADMIN_REALM=${KEYCLOAK_ADMIN_REALM}
      - KEYCLOAK_ADMIN_CLIENT_ID=${KEYCLOAK_ADMIN_CLIENT_ID}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JVM_OPTS=${JVM_OPTS}
      - LOGGING_LEVEL_ROOT=${ROOT_LOG_LEVEL:-WARN}
      - LOGGING_LEVEL_COM_STOCKFELLOW=${LOG_LEVEL:-INFO}
    networks:
      - stockfellow-net
    volumes:
      - ./services/api-gateway/src:/app/src
      - ./services/api-gateway/src/main/resources/keycloak.json:/app/src/main/resources/keycloak.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/actuator/health"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}
      start_period: ${HEALTH_CHECK_START_PERIOD:-40s}

  # User Service (Spring Boot)
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile.dev
    container_name: user-service
    depends_on:
      - keycloak
    ports:
      - "${USER_SERVICE_PORT}:4000"
      - "${USER_SERVICE_DEBUG_PORT}:5005"
    environment:
      - SPRING_PROFILES_ACTIVE=${USER_SERVICE_SPRING_PROFILE}
      - SPRING_DATA_MONGODB_URI=${USER_SERVICE_MONGODB_URI}
      - KEYCLOAK_JWKS_URI=${KEYCLOAK_JWKS_URI}
      - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}
      - JVM_OPTS=${USER_SERVICE_JVM_OPTS}
      - LOGGING_LEVEL_ROOT=${ROOT_LOG_LEVEL:-WARN}
      - LOGGING_LEVEL_COM_STOCKFELLOW=${LOG_LEVEL:-INFO}
    networks:
      - stockfellow-net
    volumes:
      - ./services/user-service/src:/app/src
      - ./services/user-service/pom.xml:/app/pom.xml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/actuator/health"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}
      start_period: ${HEALTH_CHECK_START_PERIOD:-40s}
  
  # Group Service (Spring Boot)
  group-service:
    build:
      context: ./services/group-service
      dockerfile: Dockerfile
    container_name: group-service
    depends_on:
      - keycloak
      - user-service
    ports:
      - "${GROUP_SERVICE_PORT}:4040"
      - "${GROUP_SERVICE_DEBUG_PORT}:5006"
    environment:
      - SERVER_PORT=${GROUP_SERVICE_PORT}
      - SPRING_PROFILES_ACTIVE=${GROUP_SERVICE_SPRING_PROFILE}
      - MONGODB_URI=${GROUP_SERVICE_MONGODB_URI}
      - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}
      - KEYCLOAK_JWKS_URI=${KEYCLOAK_JWKS_URI}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - JVM_OPTS=${GROUP_SERVICE_JVM_OPTS}
      - LOGGING_LEVEL_ROOT=${ROOT_LOG_LEVEL:-WARN}
      - LOGGING_LEVEL_COM_STOCKFELLOW=${LOG_LEVEL:-INFO}
    networks:
      - stockfellow-net
    volumes:
      - ./services/group-service/src:/app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4040/actuator/health"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}
      start_period: ${HEALTH_CHECK_START_PERIOD:-40s}

  # Transaction Service
  transaction-service:
    build:
      context: ./services/transaction-service
      dockerfile: Dockerfile
    container_name: transaction-service
    depends_on:
      - group-service
      - user-service
    ports:
      - "${TRANSACTION_SERVICE_PORT}:4080"
    environment:
      - SERVER_PORT=${TRANSACTION_SERVICE_PORT}
      - SPRING_PROFILES_ACTIVE=${TRANSACTION_SERVICE_SPRING_PROFILE}
      - TRANSACTIONDB_URI=${TRANSACTIONDB_URI}
      - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}
      - KEYCLOAK_JWKS_URI=${KEYCLOAK_JWKS_URI}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - GROUP_SERVICE_URL=${GROUP_SERVICE_URL}
      - JVM_OPTS=${TRANSACTION_SERVICE_JVM_OPTS}
      - LOGGING_LEVEL_ROOT=${ROOT_LOG_LEVEL:-WARN}
      - LOGGING_LEVEL_COM_STOCKFELLOW=${LOG_LEVEL:-INFO}
    networks:
      - stockfellow-net
    volumes:
      - ./services/transaction-service/src:/app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4080/actuator/health"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}
      start_period: ${HEALTH_CHECK_START_PERIOD:-40s}

  # Notification Service
  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    depends_on:
      - notification-postgres
      - activemq
      - group-service
    ports:
      - "4050:4050"
      - "5008:5008"  # Debug port
    environment:
      - SERVER_PORT=4050
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://notification-postgres:5432/notification_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin123
      - ACTIVEMQ_BROKER_URL=tcp://activemq:61616
      - ACTIVEMQ_USER=admin
      - ACTIVEMQ_PASSWORD=admin
      - SERVICES_GROUP_SERVICE_URL=http://group-service:4040
      - SERVICES_USER_SERVICE_URL=http://user-service:4000
      - JVM_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008
      - LOGGING_LEVEL_ROOT=WARN
      - LOGGING_LEVEL_COM_STOCKFELLOW=INFO
    networks:
      - stockfellow-net
    volumes:
      - ./services/notification-service/src:/app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4050/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
# MFA Service (Spring Boot)
  mfa-service:
    build:
      context: ./services/mfa-service
      dockerfile: Dockerfile
    container_name: mfa-service
    depends_on:
      - keycloak
      - user-service
    ports:
      - "${MFA_SERVICE_PORT}:8087"  # Changed from 4090 to 8087
      - "${MFA_SERVICE_DEBUG_PORT}:5008"
    environment:
      - SERVER_PORT=8087  # Override to ensure port is 8087
      - SPRING_PROFILES_ACTIVE=${MFA_SERVICE_SPRING_PROFILE}
      - MONGODB_URI=${MFA_SERVICE_MONGODB_URI}
      - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}
      - KEYCLOAK_JWKS_URI=${KEYCLOAK_JWKS_URI}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - JVM_OPTS=${MFA_SERVICE_JVM_OPTS}
      - LOGGING_LEVEL_ROOT=${ROOT_LOG_LEVEL:-WARN}
      - LOGGING_LEVEL_COM_STOCKFELLOW=${LOG_LEVEL:-INFO}
      # Mail configuration
      - MFA_MAIL_HOST=${MFA_MAIL_HOST}
      - MFA_MAIL_PORT=${MFA_MAIL_PORT}
      - MFA_MAIL_USERNAME=${MFA_MAIL_USERNAME}
      - MFA_MAIL_PASSWORD=${MFA_MAIL_PASSWORD}
      - MFA_MAIL_FROM=${MFA_MAIL_FROM}
      - MFA_MAIL_STARTTLS=${MFA_MAIL_STARTTLS}
      - MFA_MAIL_SSL=${MFA_MAIL_SSL}
    networks:
      - stockfellow-net
    volumes:
      - ./services/mfa-service/src:/app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8087/actuator/health"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}
      start_period: ${HEALTH_CHECK_START_PERIOD:-40s}

networks:
  stockfellow-net:
    driver: bridge

volumes:
  postgres_data:
  notification_postgres_data:
  mongodb_data:
  redis_data:
  activemq_data: