global: 
  scrape_interval: 15s 
  evaluation_interval: 15s 
 
scrape_configs: 
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['localhost:9090'] 
 
  - job_name: 'cadvisor' 
    static_configs: 
      - targets: ['cadvisor:8080'] 
 
  - job_name: 'spring-boot' 
    static_configs: 
      - targets: ['api-gateway:3000', 'user-service:4020', 'group-service:4040'] 
    metrics_path: '/actuator/prometheus' 
