# MFA Service - Production optimized
services:
  mfa-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mfa-service
    deploy:
      resources:
        limits:
          cpus: '0.125'
          memory: 256M
        reservations:
          cpus: '0.0625'
          memory: 128M
    ports:
      - "${MFA_SERVICE_PORT:-8087}:8087"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - KEYCLOAK_ISSUER=http://keycloak:8080/realms/stockfellow
      - KEYCLOAK_JWKS_URI=${KEYCLOAK_JWKS_URI}
      - USER_SERVICE_URL=http://user-service:4020
      - LOGGING_LEVEL_ROOT=WARN
      - LOGGING_LEVEL_COM_STOCKFELLOW=INFO
      - MFA_MAIL_HOST=${MFA_MAIL_HOST}
      - MFA_MAIL_PORT=${MFA_MAIL_PORT}
      - MFA_MAIL_USERNAME=${MFA_MAIL_USERNAME}
      - MFA_MAIL_PASSWORD=${MFA_MAIL_PASSWORD}
    networks:
      - stockfellow-prod
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8087/actuator/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 90s
    restart: unless-stopped

networks:
  stockfellow-prod:
    external: true