# Dockerfile for User Service
   services:
     user-service:
       build: .
       ports:
         - "5000:5000"
       environment:
         - DB_URL=mongodb://mongodb:27017/stokvel
       depends_on:
         - mongodb
       networks:
         - stockfellow-net
       command: npm start
     mongodb:
       image: mongo:latest
       networks:
         - stockfellow-net
       volumes:
         - mongodb-data:/data/db

   networks:
     stockfellow-net:
       driver: bridge

   volumes:
     mongodb-data:
