user-service:
  build:
    context: ./services/user-service
    dockerfile: Dockerfile
  container_name: user-service
  deploy:
    resources:
      limits:
        cpus: '0.25'
        memory: 512M
      reservations:
        cpus: '0.125'
        memory: 256M
  depends_on:
    - postgres
    - keycloak
  ports:
    - "${USER_SERVICE_PORT:-4020}:4020"
  environment:
    - SPRING_PROFILES_ACTIVE=prod
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/userservice_db
    - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
    - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    - KEYCLOAK_JWKS_URI=${KEYCLOAK_JWKS_URI}
    - KEYCLOAK_ISSUER=http://keycloak:8080/realms/stockfellow
    - LOGGING_LEVEL_ROOT=WARN
    - LOGGING_LEVEL_COM_STOCKFELLOW=INFO
    - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    - SPRING_JPA_SHOW_SQL=false
    - POSTGRES_USER=${POSTGRES_USER:-postgres}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    - POSTGRES_DB=userservice_db 
  networks:
    - stockfellow-prod
  healthcheck:
    test: ["CMD-SHELL", "curl -f http://localhost:4020/actuator/health || exit 1"]
    interval: 60s
    timeout: 10s
    retries: 3
    start_period: 90s
  restart: unless-stopped