server:
  port: ${MFA_SERVICE_PORT:8087}

spring:
  application:
    name: mfa-service

app:
  mail:
    from: ${MFA_MAIL_FROM}
    provider: sendgrid
    sendgrid:
      api-key: ${SENDGRID_API_KEY} # <-- add this
  mfa:
    otp:
      length: 6
      expiry-minutes: 5

logging:
  level:
    com.stockfellow.mfa: DEBUG
    root: ${ROOT_LOG_LEVEL:WARN}
