spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0&preparedStatementCacheQueries=0&preparedStatementCacheSizeMiB=0
    username: postgres.lcrdisuesrfbohqvudus
    password: DevOpps123@
    driver-class-name: org.postgresql.Driver

    # Connection pool settings
    hikari:
        maximum-pool-size: 3
        minimum-idle: 1
        connection-timeout: 30000
        idle-timeout: 300000
        max-lifetime: 600000
        auto-commit: true
        
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Africa/Johannesburg
          batch_size: 0
        connection:
          provider_disables_autocommit: false

scheduler:
  debit-order-cron: "0 0 1 * * ?" # Run at 1 AM on the 1st of every month
  payout-cron: "0 0 2 * * ?" # Run at 2 AM on the 2nd of every month

server:
  port: 4080 # was 4042

logging:
  level:
    com.stockfellow: DEBUG

# Add this section for actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,mappings
  endpoint:
    health:
      show-details: always
