spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stokvel_db
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
directdebit:
  api:
    base-url: https://api.directdebit.co.za
    client-id: your_client_id
    client-secret: your_client_secret
    mandate-endpoint: /v1/mandates
    debit-order-endpoint: /v1/debit-orders
    payout-endpoint: /v1/payouts
scheduler:
  debit-order-cron: "0 0 1 * * ?" # Run at 1 AM on the 1st of every month
  payout-cron: "0 0 2 * * ?"    # Run at 2 AM on the 2nd of every month
server:
  port: 4042
logging:
  level:
    com.stockfellow: DEBUG