spring:
  application:
    name: transaction-service
  datasource:
    # CORRECTED: Using the actual Supabase connection details
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.lcrdisuesrfbohqvudus # CORRECTED: Full username from connection string
    password: DevOpps123@ #DevOpps123%40 if that doesn't work
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Africa/Johannesburg

  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

directdebit:
  api:
    base-url: https://api.directdebit.co.za
    client-id: your_client_id
    client-secret: your_client_secret
    mandate-endpoint: /v1/mandates
    debit-order-endpoint: /v1/debit-orders
    payout-endpoint: /v1/payouts

scheduler:
  debit-order-cron: "0 0 1 * * ?" # Run at 1 AM on the 1st of every month
  payout-cron: "0 0 2 * * ?" # Run at 2 AM on the 2nd of every month

server:
  port: 4042

logging:
  level:
    com.stockfellow: DEBUG
