services:
  transaction-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction-service
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
      reservations:
        cpus: '0.125'
        memory: 256M
  ports:
    - "${TRANSACTION_SERVICE_PORT:-4080}:4080"
  environment:
    - SPRING_PROFILES_ACTIVE=prod
    - TRANSACTIONDB_URI=${TRANSACTIONDB_URI}
    - TRANSACTIONDB_USER=${TRANSACTIONDB_USER}
    - TRANSACTIONDB_PASS=${TRANSACTIONDB_PASS}
    - PAYSTACK_TEST_API_KEY=${PAYSTACK_TEST_API_KEY}
    - CALLBACK_BASE_URL=${PAYSTACK_CALLBACK_URL}
    - KEYCLOAK_ISSUER=http://keycloak:8080/realms/stockfellow
    - KEYCLOAK_JWKS_URI=${KEYCLOAK_JWKS_URI}
    - USER_SERVICE_URL=http://user-service:4020
    - GROUP_SERVICE_URL=http://group-service:4040
    - LOGGING_LEVEL_ROOT=WARN
    - LOGGING_LEVEL_COM_STOCKFELLOW=INFO
  networks:
    - stockfellow-prod
  healthcheck:
    test: ["CMD-SHELL", "curl -f http://localhost:4080/actuator/health || exit 1"]
    interval: 45s
    timeout: 10s
    retries: 3
    start_period: 90s
  restart: unless-stopped

networks:
  stockfellow-prod:
    external: true