# Group service - Production optimized
services:
  group-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: group-service
    deploy:
      resources:
        limits:
          cpus: '0.125'
          memory: 256M
        reservations:
          cpus: '0.0625'
          memory: 128M
    ports:
      - "${GROUP_SERVICE_PORT:-4040}:4040"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGODB_URI=${GROUP_SERVICE_MONGODB_URI}
      - KEYCLOAK_ISSUER=http://keycloak:8080/realms/stockfellow
      - KEYCLOAK_JWKS_URI=${KEYCLOAK_JWKS_URI}
      - USER_SERVICE_URL=http://user-service:4020
      - LOGGING_LEVEL_ROOT=WARN
      - LOGGING_LEVEL_COM_STOCKFELLOW=INFO
    networks:
      - stockfellow-prod
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4040/actuator/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 90s
    restart: unless-stopped

networks:
  stockfellow-prod:
    external: true