server:
  port: 3000

  tomcat:
    threads:
      max: 50         
      min-spare: 5     
    max-connections: 500  
    accept-count: 100     
    connection-timeout: 20000ms
    max-http-header-size: 8KB

  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 1024

spring:
  application:
    name: api-gateway

  # jpa:
  #   open-in-view: false

  # Redic Config
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 4
        max-idle: 2
        min-idle: 1
        max-wait: 1000ms
      shutdown-timeout: 100ms
    connect-timeout: 1000ms
    command-timeout: 1000ms
  
  cache:
    type: redis
    redis:
      time-to-live: 300000ms
      cache-null-values: false
  
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: true 

  security:
    sessions: never  # Stateless for microservices

# Management endpoints - Minimal set for memory savings
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics  # Only essential endpoints
    jmx:
      exposure:
        exclude: "*"  # Disable JMX to save memory
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    enable:
      jvm: false          # Disable detailed JVM metrics
      process: false      # Disable process metrics
      system: false       # Disable system metrics
    export:
      simple:
        enabled: false    # Disable metrics export to save memory

keycloak:
  realm: ${KEYCLOAK_REALM:stockfellow}
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080/}
  ssl-required: external
  resource: ${KEYCLOAK_FRONTEND_CLIENT_ID:frontend-client}
  public-client: true
  confidential-port: 0
  # Connection pool for Keycloak HTTP client
  connection-pool-size: 5    # Limit concurrent connections
  socket-timeout-millis: 3000
  connection-timeout-millis: 2000

# Admin configuration
app:
  keycloak:
    gateway:
      client-id: ${KEYCLOAK_GATEWAY_CLIENT_ID:api-gateway-client}
      client-secret: ${KEYCLOAK_GATEWAY_CLIENT_SECRET:}
    frontend:
      client-id: ${KEYCLOAK_FRONTEND_CLIENT_ID:public-client}
      redirect-uri: ${KEYCLOAK_FRONTEND_REDIRECT_URI:http://localhost:3000/auth/callback}
    admin:
      username: ${KEYCLOAK_ADMIN_USERNAME:admin}
      password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
      realm: ${KEYCLOAK_ADMIN_REALM:master}
      client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
  mfa:
    enabled: true

mfa:
  service:
    url: http://localhost:8087
    # HTTP client optimizations
    connection-timeout: 2000ms
    read-timeout: 5000ms
    max-connections: 5

# Logging configuration - Optimized for memory
logging:
  level:
    # Reduce logging verbosity to save memory and CPU
    root: WARN
    com.stockfellow.gateway: INFO
    org.springframework.web: WARN  # Changed from DEBUG
    org.springframework.security: WARN
    org.springframework.boot.actuate: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  # Async logging to improve performance
  config: classpath:logback-spring.xml

# CORS configuration
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "Content-Type,Authorization"
  max-age: 3600  # Cache preflight requests

# HTTP client configurations for downstream services
http:
  client:
    connection-timeout: 2000ms
    read-timeout: 5000ms
    max-connections-per-route: 5
    max-connections-total: 12