# MINIMAL CONFIG - Let Docker/Environment handle most settings
server:
  port: 3000

spring:
  application:
    name: api-gateway

  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 4
        max-idle: 2
        min-idle: 1
        max-wait: 1000ms

  jackson:
    default-property-inclusion: NON_NULL

  cache:
    type: redis

keycloak:
  realm: ${KEYCLOAK_REALM:stockfellow}
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://keycloak:8080/}
  ssl-required: external
  resource: ${KEYCLOAK_FRONTEND_CLIENT_ID:frontend-client}
  public-client: true
  confidential-port: 0

app:
  keycloak:
    gateway:
      client-id: ${KEYCLOAK_GATEWAY_CLIENT_ID:api-gateway-client}
      client-secret: ${KEYCLOAK_GATEWAY_CLIENT_SECRET}
    frontend:
      client-id: ${KEYCLOAK_FRONTEND_CLIENT_ID:public-client}
      redirect-uri: ${KEYCLOAK_FRONTEND_REDIRECT_URI:http://localhost:3000/auth/callback}
    admin:
      username: ${KEYCLOAK_ADMIN_USERNAME:admin}
      password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
      realm: ${KEYCLOAK_ADMIN_REALM:master}
      client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
  mfa:
    enabled: true

# mfa:
#   service:
#     url: ${MFA_SERVICE_URL:http://mfa-service:8087}

services:
  user-service:
    url: ${USER_SERVICE_URL:http://user-service:4020}
  group-service:
    url: ${GROUP_SERVICE_URL:http://group-service:4040}
  transaction-service:
    url: ${TRANSACTION_SERVICE_URL:http://transaction-service:4060}
  notification-service:
    url: ${NOTIFICATION_SERVICE_URL:http://notification-service:4080}
  mfa-service:
    url: ${MFA_SERVICE_URL:http://mfa-service:8087}

cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "Content-Type,Authorization"
