spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://${DROPLET1_IP:postgres}:${POSTGRES_PORT:5432}/notification_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  activemq:
    broker-url: tcp://${DROPLET1_IP}:${ACTIVEMQ_PORT:61616}
    user: ${ACTIVEMQ_USER}
    password: ${ACTIVEMQ_PASSWORD}
    packages:
      trust-all: true
  jms:
    listener:
      auto-startup: true
      acknowledge-mode: auto
      concurrency: 1
      max-concurrency: 10

server:
  port: 4050

services:
  user-service:
    url: ${USER_SERVICE_URL:http://user-service:4020}
  group-service:
    url: ${GROUP_SERVICE_URL:http://group-service:4040}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: WARN
    com.stockfellow: INFO
    org.springframework.jms: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"